/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_s_coursework;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Andrew JR
 */
public class EmployeeListGUI extends javax.swing.JFrame {

    /**
     * Creates new form cutomerList
     */
    public EmployeeListGUI() {
        initComponents();
        printEmployeeDetails();
    }

    private void printEmployeeDetails() {
        List<employee_ws.EmployeeList> employees = getDetails();

        if (employees.get(0).getName().equals(null)) {
            errorMessage.setText("No Employee Found");
        } else {
            GridLayout experimentLayout = new GridLayout(0, 3);
            dynamicPanel.setLayout(experimentLayout);
            JLabel lblName = new JLabel("NAME");
            lblName.setForeground(Color.BLACK);
            lblName.setFont(new Font("Serif", Font.PLAIN, 18));
            lblName.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            
            JLabel lblUsername = new JLabel("USERNAME");
            lblUsername.setForeground(Color.BLACK);
            lblUsername.setFont(new Font("Serif", Font.PLAIN, 18));
            lblUsername.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            
            JLabel lblManage = new JLabel("");
            lblManage.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            
            dynamicPanel.add(lblName);
            dynamicPanel.add(lblUsername);
            dynamicPanel.add(lblManage);
            JButton[] buttons = new JButton[employees.size()];
            JLabel[] lblNames = new JLabel[employees.size()];
            JLabel[] lblUsernames = new JLabel[employees.size()];
            int employeeNumber = 0;
            while (employeeNumber < employees.size()) {
                buttons[employeeNumber] = new JButton("EDIT/DELETE");
                lblNames[employeeNumber] = new JLabel(employees.get(employeeNumber).getName());
                lblUsernames[employeeNumber] = new JLabel(employees.get(employeeNumber).getUserName());
                employee_ws.EmployeeList currentEmployee = employees.get(employeeNumber);
                buttons[employeeNumber].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        setVisible(false);
                        new EditOrDeleteEmployeeDetails(currentEmployee).setVisible(true);
                    }
                });
                lblNames[employeeNumber].setForeground(Color.BLACK);
                lblNames[employeeNumber].setFont(new Font("Serif", Font.PLAIN, 16));
                lblNames[employeeNumber].setBorder(BorderFactory.createLineBorder(Color.BLACK));

                lblUsernames[employeeNumber].setForeground(Color.BLACK);
                lblUsernames[employeeNumber].setFont(new Font("Serif", Font.PLAIN, 16));
                lblUsernames[employeeNumber].setBorder(BorderFactory.createLineBorder(Color.BLACK));

                dynamicPanel.add(lblNames[employeeNumber]);
                dynamicPanel.add(lblUsernames[employeeNumber]);
                dynamicPanel.add(buttons[employeeNumber]);

                employeeNumber++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerListPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        backLink = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        addEmployee = new javax.swing.JButton();
        dynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backLink.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        backLink.setText("BACK");
        backLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLinkMouseClicked(evt);
            }
        });

        errorMessage.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N

        addEmployee.setBackground(new java.awt.Color(51, 255, 51));
        addEmployee.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        addEmployee.setText("ADD EMPLOYEE'");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(backLink, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addEmployee))))
            .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backLink, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addEmployee))
        );

        javax.swing.GroupLayout customerListPanelLayout = new javax.swing.GroupLayout(customerListPanel);
        customerListPanel.setLayout(customerListPanelLayout);
        customerListPanelLayout.setHorizontalGroup(
            customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customerListPanelLayout.setVerticalGroup(
            customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLinkMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new subMenuPage("BACK").setVisible(true);
    }//GEN-LAST:event_backLinkMouseClicked

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new signupPage().setVisible(true);

    }//GEN-LAST:event_addEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployee;
    private javax.swing.JLabel backLink;
    private javax.swing.JPanel customerListPanel;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<employee_ws.EmployeeList> getDetails() {
        employee_ws.Employee_Service service = new employee_ws.Employee_Service();
        employee_ws.Employee port = service.getEmployeePort();
        return port.getDetails();
    }
}
