/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_s_coursework;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew JR
 */
public class signupPage extends javax.swing.JFrame {

    /**
     * Creates new form signupPage
     */
    public signupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupPanel = new javax.swing.JPanel();
        sigupMessage = new javax.swing.JLabel();
        usernameMessage = new javax.swing.JLabel();
        positionMessage = new javax.swing.JLabel();
        passwordMessage = new javax.swing.JLabel();
        nameMessage = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        backLable = new javax.swing.JLabel();
        helpLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        ClearButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sig-Up");

        signupPanel.setPreferredSize(new java.awt.Dimension(420, 300));

        sigupMessage.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        sigupMessage.setText("  SIGUP ");

        usernameMessage.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        usernameMessage.setText("   USERNAME");

        positionMessage.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        positionMessage.setText("    POSITION");

        passwordMessage.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        passwordMessage.setText("   PASSWORD");

        nameMessage.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        nameMessage.setText("        NAME");

        name.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N

        username.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        position.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N

        register.setBackground(new java.awt.Color(0, 255, 0));
        register.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        backLable.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        backLable.setText("BACK");
        backLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLableMouseClicked(evt);
            }
        });

        helpLabel.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        helpLabel.setText("   HELP");
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });

        password.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N

        ClearButton.setBackground(new java.awt.Color(255, 0, 0));
        ClearButton.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        errorMessage.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(sigupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(backLable)
                .addGap(19, 19, 19))
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(password)
                    .addComponent(name))
                .addContainerGap())
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(positionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(position)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(register)
                .addGap(21, 21, 21))
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupPanelLayout.setVerticalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigupMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backLable))
                .addGap(41, 41, 41)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(nameMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(register)
                    .addComponent(errorMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpLabel)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void backLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLableMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new welcomePage().setVisible(true);
    }//GEN-LAST:event_backLableMouseClicked

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new signUpHelp().setVisible(true);
    }//GEN-LAST:event_helpLabelMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String userName = name.getText().toLowerCase();
        String userUserName = username.getText().toLowerCase();
        String userPassword = password.getText();
        String userPosition = position.getText().toLowerCase();

        if (!userName.equals("") || !userUserName.equals("") || !userPassword.equals("") || !userPosition.equals("")) {
            boolean result = createEmployee(userName, userPosition, userUserName, userPassword);
            if (result) {
                //JOptionPane.showMessageDialog(null, "Successfull Message", "Employee Created Successfull", JOptionPane.ERROR_MESSAGE);
                errorMessage.setText("Employee Created");
            } else {
                //JOptionPane.showMessageDialog(null, "Error Message", "Sorry Try Again", JOptionPane.ERROR_MESSAGE);
                errorMessage.setText("Employee Created");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Successfull Message", "Fill The Form Correctly", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_registerActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        name.setText("");
        password.setText("");
        position.setText("");
        username.setText("");

    }//GEN-LAST:event_ClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel backLable;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameMessage;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordMessage;
    private javax.swing.JTextField position;
    private javax.swing.JLabel positionMessage;
    private javax.swing.JButton register;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JLabel sigupMessage;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameMessage;
    // End of variables declaration//GEN-END:variables

    private static boolean createEmployee(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        employee_ws.Employee_Service service = new employee_ws.Employee_Service();
        employee_ws.Employee port = service.getEmployeePort();
        return port.createEmployee(arg0, arg1, arg2, arg3);
    }


}
