/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_s_coursework;

/**
 *
 * @author Andrew JR
 */
public class subMenuPage extends javax.swing.JFrame {

    /**
     * Creates new form subMenuPage
     */
    public subMenuPage() {
        initComponents();
    }
    
    
    public subMenuPage(String userUserName){
        initComponents();
        username.setText(userUserName.toUpperCase());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subMenuLabel = new javax.swing.JPanel();
        emoloyee = new javax.swing.JLabel();
        welcomeTitle = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        customerList = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANK SYSTEM");

        subMenuLabel.setPreferredSize(new java.awt.Dimension(420, 300));

        emoloyee.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        emoloyee.setText("         EMPLOYEE PAGE");
        emoloyee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emoloyeeMouseClicked(evt);
            }
        });

        welcomeTitle.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        welcomeTitle.setText("    WELCOME ");

        username.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        username.setText("      <!username>");

        customerList.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        customerList.setText("          CUSTOMER LIST");
        customerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerListMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Serif", 2, 11)); // NOI18N
        logout.setText("LOG-OUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout subMenuLabelLayout = new javax.swing.GroupLayout(subMenuLabel);
        subMenuLabel.setLayout(subMenuLabelLayout);
        subMenuLabelLayout.setHorizontalGroup(
            subMenuLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuLabelLayout.createSequentialGroup()
                .addGroup(subMenuLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subMenuLabelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(welcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addGroup(subMenuLabelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(subMenuLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emoloyee, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        subMenuLabelLayout.setVerticalGroup(
            subMenuLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuLabelLayout.createSequentialGroup()
                .addGroup(subMenuLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subMenuLabelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(subMenuLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(welcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(emoloyee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   


    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:

        // save every thing before redricting
        this.setVisible(false);
        new welcomePage().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void customerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerListMouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
        new CustomerListGUI().setVisible(true);
    }//GEN-LAST:event_customerListMouseClicked

    private void emoloyeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emoloyeeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new EmployeeListGUI().setVisible(true);
    }//GEN-LAST:event_emoloyeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subMenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subMenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerList;
    private javax.swing.JLabel emoloyee;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel subMenuLabel;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcomeTitle;
    // End of variables declaration//GEN-END:variables
}
